# Obviously we don't need PHP for our FE, but it saves downloading multiple images and gives you some options
FROM trafex/php-nginx

# Where our code is volume mounted
WORKDIR /var/www/html

EXPOSE 8080